#!/bin/bash

echo "+-------------------------+"
echo "|   Generated by Eureka   |"
echo "+-------------------------+"
echo

echo -n "Started  at " 
date


# Write here your code


echo -n "Finished at " 
date
